language: bash
services: docker

env:
  - VARIANT=latest
  - VARIANT=cli

before_script:
  - env | sort
  - cd "$VARIANT"
  - image="joshbetz/wordpress:${VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ../test/run.sh "$image"

after_script:
  - docker images
